import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  techblogSidebar: [
    {
      type: 'category',
      label: '프로젝트',
      items: [
        'projects/도큐사우루스 블로그 개설하기/docusaurus_001_20250130'
        // 추가 프로젝트들
      ],
    },
    {
      type: 'category',
      label: '기술',
      items: [
        'skills/Python',
        // 추가 기술 스택
      ],
    }
  ]

  
};

export default sidebars;
