import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  portfolioSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Projects',
      items: [
        'projects/project1',
        // 추가 프로젝트들
      ],
    },
    {
      type: 'category',
      label: 'Skills & Experience',
      items: [
        'skills/Python',
        // 추가 기술 스택
      ],
    },
  ],

  
};

export default sidebars;
